---
roles:
  - name: inmotionhosting.apache
    version: "3.0.0"

  - name: inmotionhosting.mysql
    version: "2.3.0"

  - name: inmotionhosting.nginx_proxy
    version: "3.0.1"

  - name: inmotionhosting.php_fpm
    version: "3.0.1"

  - name: inmotionhosting.redis
    version: "2.3.0"
collections:
  - name: community.general
  - name: community.mysql
  - name: ansible.posix
