---
roles:
  - name: inmotionhosting.apache
  - name: inmotionhosting.mysql
  - name: inmotionhosting.php_fpm
  - name: inmotionhosting.nginx_proxy
collections:
  - community.docker
  - community.general
  - ansible.posix
