---
roles:
  - name: inmotionhosting.apache
  - name: inmotionhosting.mysql
  - name: inmotionhosting.php_fpm
  - name: inmotionhosting.nginx_proxy
  - name: inmotionhosting.redis
collections:
  - name: https://github.com/ansible-collections/community.general
    type: git
  - name: https://github.com/ansible-collections/community.docker
    type: git
  - name: https://github.com/ansible-collections/ansible.posix
    type: git
