---
roles:
  - name: inmotionhosting.apache
  - name: inmotionhosting.mysql
  - name: inmotionhosting.php_fpm
  - name: inmotionhosting.nginx_proxy
collections:
  - name: community.docker
  - name: community.general
  - name: ansible.posix
