---
- name: Set lists of required variables
  ansible.builtin.set_fact:
    wp_required_strings:
      - system_user
      - pass_gen_alias
      - wp_system_path
      - wp_system_folder
      - wp_db_name
      - wp_db_user
      - wp_cli_source
      - site_domain
      - site_email
      - site_user
      - site_pass
    wp_required_ints:
      - php_proc_mem

- name: Check required WordPress variables (strings)
  ansible.builtin.fail:
    msg: |
      Invalid value for variable for '{{ item }}': {{ lookup('vars', item) }}

      Supported types  : String
      Supported values : Any non-null string
  when: >-
    lookup('vars', item) is not string
    or lookup('vars', item) == 0
  with_items: "{{ wp_required_strings }}"

- name: Check required WordPress variables (integers)
  ansible.builtin.fail:
    msg: |
      Invalid value for variable for '{{ item }}': {{ lookup('vars', item) }}

      Supported types  : Integer
      Supported values : A number between 0-65535
  when: >-
    lookup('vars', item)|int < 0
    or lookup('vars', item)|int > 65535
  with_items: "{{ wp_required_ints }}"

- name: Check required WordPress variables (children_buffer)
  ansible.builtin.fail:
    msg: |
      Invalid value for variable for '{{ children_buffer }}': {{ children_buffer }}

      Supported types  : Float
      Supported values : A number between 0.0-1.0
  when: >-
    children_buffer|float < 0.0
    or children_buffer|float >= 1.0
