---
- name: (Python 3) Install SELinux management packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - libselinux-python3
    - policycoreutils-python3
    - libsemanage-python3
  when: ansible_python_version is version('3.0', '>=')

- name: (Python 2) Install SELinux management packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - libselinux-python
    - policycoreutils-python
    - libsemanage-python
  when: ansible_python_version is version('3.0', '<')

- name: Enable SELinux
  ansible.posix.selinux:
    policy: targeted
    state: enforcing

- name: Register file context for Wordpress doc root
  community.general.sefcontext:
    target: "{{ wp_system_path }}(/.*)?"
    setype: httpd_sys_rw_content_t
    state: present
  register: filecontext_docroot

- name: Run restore context to doc root
  command: "restorecon -Rv /home/{{ system_user }}"
  when: filecontext_docroot.changed

- name: Set SELinux booleans
  ansible.posix.seboolean:
    name: "{{ item }}"
    state: yes
    persistent: yes
  with_items: "{{ selinux_booleans }}"
