---
- name: Check if wp-cli is installed
  stat:
    path: /usr/bin/wp
  changed_when: false
  register: wpcli_installed

- name: Install wp-cli if missing
  get_url:
    url: "{{ wp_cli_source }}"
    dest: /usr/bin/wp
    mode: a+x
  when: not wpcli_installed.stat.exists

#
# MySQL
#

- name: Set random MySQL password when not defined
  set_fact:
    wp_db_pass: "{{ pass_gen_alias }}"
  when: wp_db_pass is undefined

- name: Create WordPress database
  mysql_db:
    login_unix_socket: "{{ mysql_socket_path }}"
    name: "{{ wp_db_name }}"
    state: present
  register: wp_db_setup

- name: Create DB user
  mysql_user:
    login_unix_socket: "{{ mysql_socket_path }}"
    name: "{{ wp_db_user }}"
    password: "{{ wp_db_pass }}"
    priv: "{{ wp_db_name }}.*:ALL"
    state: present

#
# WordPress
#
- name: Ensure install directory exists
  file:
    path: "{{ wp_system_path }}"
    state: directory
    owner: "{{ system_user }}"
    group: "{{ system_user }}"
    mode: "0755"

- name: Download WordPress Core
  command: >-
    wp core download
  args:
    chdir: "{{ wp_system_path }}"
    creates: "{{ wp_system_path }}/index.php"
  become: true
  become_user: "{{ system_user }}"

- name: Create wp-config.php
  command: >-
    wp config create
    --dbname="{{ wp_db_name }}"
    --dbuser="{{ wp_db_user }}"
    --dbpass="{{ wp_db_pass }}"
  args:
    chdir: "{{ wp_system_path }}"
    creates: "{{ wp_system_path }}/wp-config.php"
  become: true
  become_user: "{{ system_user }}"

- name: Install WordPress core
  command: >-
    wp core install
    --url="{{ site_domain }}"
    --title="{{ site_domain }}"
    --admin_user="{{ site_user }}"
    --admin_password="{{ site_pass }}"
    --admin_email="{{ site_email }}"
    --skip-email
  args:
    chdir: "{{ wp_system_path }}"
  become: true
  become_user: "{{ system_user }}"

- name: Ensure "{{ wp_system_path }}/wp-*/" permissions are correct
  ansible.builtin.file:
    path: "{{ wp_system_path }}/{{ item.path }}/"
    state: directory
    owner: "{{ system_user }}"
    group: "{{ system_user }}"
    mode: "0755"
  loop:
    - path: wp-admin
    - path: wp-content
    - path: wp-includes

#
# Plugins
#

- name: Install plugins
  command: >-
    wp plugin install {{ item }} --activate
  args:
    chdir: "{{ wp_system_path }}"
    creates: "{{ wp_system_path }}/wp-content/plugins/{{ item }}"
  become: true
  become_user: "{{ system_user }}"
  when:
    - wp_plugins is defined
    - wp_plugins | length > 0
  with_items: "{{ wp_plugins }}"

- name: Uninstall default plugins
  command: >-
    wp plugin uninstall hello
  args:
    chdir: "{{ wp_system_path }}"
    removes: "{{ wp_system_path }}/wp-content/plugins/hello.php"
  become: true
  become_user: "{{ system_user }}"

- name: Configure W3 Total Cache
  command: >-
    wp w3-total-cache option set
    {{ item.setting }} {{ item.value }} --type={{ item.type }}
  args:
    chdir: "{{ wp_system_path }}"
  become: true
  become_user: "{{ system_user }}"
  when:
    - wp_plugins is defined
    - wp_plugins | length > 0
    - ("w3-total-cache" in wp_plugins)
  with_items: "{{ wp_w3tc_settings }}"

#
# Themes
#

- name: Install themes
  command: >-
    wp theme install {{ item }} --activate
  args:
    chdir: "{{ wp_system_path }}"
    creates: "{{ wp_system_path }}/wp-content/themes/{{ item }}"
  become: true
  become_user: "{{ system_user }}"
  when:
    - wp_themes is defined
    - wp_themes | length > 0
  with_items: "{{ wp_themes }}"
