---
- name: Restart apache
  ansible.builtin.service:
    name: "{{ apache_daemon }}"
    state: restarted
  when: apache_syntax.rc == 0

- name: Restart mysql
  ansible.builtin.service:
    name: "{{ mysql_daemon }}"
    state: restarted

- name: Restart php-fpm
  ansible.builtin.service:
    name: "{{ php_fpm_daemon }}"
    state: restarted
  when: phpfpm_syntax.rc == 0

- name: Restart nginx
  ansible.builtin.service:
    name: nginx
    state: restarted
  when: nginx_syntax.rc == 0
