---
- name: Converge
  hosts: all

  pre_tasks:
    - name: Update apt cache (on Debian).
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
      when: ansible_os_family == 'Debian'

  roles:
    - role: ansible-role-wordpress
      vars:
        use_letsencrypt: false
