{% if item.registry is defined %}
FROM {{ item.registry.url }}/{{ item.image }}
{% else %}
FROM {{ item.image }}
{% endif %}

RUN if [ "$(command -v apt)" ]; then \
        apt update && \
        apt install -y --no-install-recommends --no-install-suggests \
            ca-certificates openssh-client openssh-server openssl python3 \
            sudo systemd && \
        apt autoremove -y && \
        apt clean -y; \
    elif [ "$(command -v dnf)" ]; then \
        dnf install -y ca-certificates hostname openssh openssh-server \
            openssl python3 sudo systemd which && \
        dnf autoremove -y && \
        dnf clean all; \
    elif [ "$(command -v yum)" ]; then \
        yum install -y ca-certificates hostname openssh openssh-server \
            openssl python3 sudo systemd which && \
        yum autoremove -y && \
        yum clean all; \
    fi

RUN rm -rf /lib/systemd/system/{*getty*,systemd*udev*} && \
    cp /bin/true /sbin/agetty && \
    echo "Defaults !requiretty" >> /etc/sudoers

VOLUME ["/sys/fs/cgroup"]

{% if "centos" in item.image %}
CMD ["/usr/lib/systemd/systemd"]
{% else %}
CMD ["/lib/systemd/systemd"]
{% endif %}
