---
dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: "molecule-ansible-role-monit"
    image: ${MOLECULE_IMAGE:-geerlingguy/docker-ubuntu2204-ansible:latest}
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true

provisioner:
  name: "ansible"
  config_options:
    defaults:
      callbacks_enabled: "profile_tasks, timer"
      internal_poll_interval: 0.01
      nocows: 1
      stdout_callback: "yaml"
      var_compression_level: 9

verifier:
  name: ansible
