name: Ansible Molecule Pipeline

on:  # yamllint disable-line rule:truthy
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  PY_COLORS: '1'
  ANSIBLE_FORCE_COLOR: '1'

jobs:
  molecule:
    name: Molecule Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - image: geerlingguy/docker-debian10-ansible:latest
            command: /lib/systemd/systemd
          - image: geerlingguy/docker-debian11-ansible:latest
            command: /lib/systemd/systemd
          - image: geerlingguy/docker-ubuntu2004-ansible:latest
          - image: geerlingguy/docker-ubuntu2204-ansible:latest
          - image: ghcr.io/artis3n/docker-almalinux8-ansible:latest
          - image: geerlingguy/docker-rockylinux8-ansible:latest
          - image: geerlingguy/docker-rockylinux9-ansible:latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install test dependencies
        run: pip install -r requirements.txt

      - name: Run Molecule Test
        run: molecule test
        env:
          MOLECULE_IMAGE: ${{ matrix.image }}
          MOLECULE_COMMAND: ${{ matrix.command }}

  molecule-legacy:
    name: Molecule Test Legacy OS
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - image: geerlingguy/docker-centos7-ansible:latest
            command: /usr/lib/systemd/systemd
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install test dependencies
        run: pip install -r requirements.txt

      - name: Run Molecule Test
        run: molecule test
        env:
          MOLECULE_IMAGE: ${{ matrix.image }}
          MOLECULE_COMMAND: ${{ matrix.command }}
